# Airbnb Europe Pricing

Objective: Explore Airbnb listing data across 10 European cities to understand pricing patterns and build a price prediction model later.

Dataset: 20 CSV files, 10 cities, weekday/weekend file per city

This notebook:
Opens each CSV file and adds a city/weekday-weekend label
Combines everything into one table
Checks columns, data types, and missing values
Removes duplicates, fixes data types, and removes price outliers
Saves the dataset as airbnb_cleaned.csv

In [6]:
import pandas as pd
import numpy as np

#import datasets
amsterdam_weekdays = pd.read_csv('../airbnb/data/amsterdam_weekdays.csv', index_col=0)
amsterdam_weekends = pd.read_csv('../airbnb/data/amsterdam_weekends.csv', index_col=0)

athens_weekdays = pd.read_csv('../airbnb/data/athens_weekdays.csv', index_col=0)
athens_weekends = pd.read_csv('../airbnb/data/athens_weekends.csv', index_col=0)

barcelona_weekdays = pd.read_csv('../airbnb/data/barcelona_weekdays.csv', index_col=0)
barcelona_weekends = pd.read_csv('../airbnb/data/barcelona_weekends.csv', index_col=0)

berlin_weekdays = pd.read_csv('../airbnb/data/berlin_weekdays.csv', index_col=0)
berlin_weekends = pd.read_csv('../airbnb/data/berlin_weekends.csv', index_col=0)

budapest_weekdays = pd.read_csv('../airbnb/data/budapest_weekdays.csv', index_col=0)
budapest_weekends = pd.read_csv('../airbnb/data/budapest_weekends.csv', index_col=0)

lisbon_weekdays = pd.read_csv('../airbnb/data/lisbon_weekdays.csv', index_col=0)
lisbon_weekends = pd.read_csv('../airbnb/data/lisbon_weekends.csv', index_col=0)

london_weekdays = pd.read_csv('../airbnb/data/london_weekdays.csv', index_col=0)
london_weekends = pd.read_csv('../airbnb/data/london_weekends.csv', index_col=0)

paris_weekdays = pd.read_csv('../airbnb/data/paris_weekdays.csv', index_col=0)
paris_weekends = pd.read_csv('../airbnb/data/paris_weekends.csv', index_col=0)

rome_weekdays = pd.read_csv('../airbnb/data/rome_weekdays.csv', index_col=0)
rome_weekends = pd.read_csv('../airbnb/data/rome_weekends.csv', index_col=0)

vienna_weekdays = pd.read_csv('../airbnb/data/vienna_weekdays.csv', index_col=0)
vienna_weekends = pd.read_csv('../airbnb/data/vienna_weekends.csv', index_col=0)

In [7]:
amsterdam_weekdays.head()

,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
0,194.033698,Private room,False,True,2.0,False,1,0,10.0,93.0,1,5.022964,2.539380,78.690379,4.166708,98.253896,6.846473,4.90569,52.41772
1,344.245776,Private room,False,True,4.0,False,0,0,8.0,85.0,1,0.488389,0.239404,631.176378,33.421209,837.280757,58.342928,4.90005,52.37432
2,264.101422,Private room,False,True,2.0,False,0,1,9.0,87.0,1,5.748312,3.651621,75.275877,3.985908,95.386955,6.646700,4.97512,52.36103
3,433.529398,Private room,False,True,4.0,False,0,1,9.0,90.0,2,0.384862,0.439876,493.272534,26.119108,875.033098,60.973565,4.89417,52.37663
4,485.552926,Private room,False,True,2.0,True,0,0,10.0,98.0,1,0.544738,0.318693,552.830324,29.272733,815.305740,56.811677,4.90051,52.37508

### Add city and weekday/weekend labels to each dataframe

In [8]:
amsterdam_weekdays['city'] = 'amsterdam'
amsterdam_weekdays['price_period'] = 'weekday'
amsterdam_weekends['city'] = 'amsterdam'
amsterdam_weekends['price_period'] = 'weekend'

athens_weekdays['city'] = 'athens'
athens_weekdays['price_period'] = 'weekday'
athens_weekends['city'] = 'athens'
athens_weekends['price_period'] = 'weekend'

barcelona_weekdays['city'] = 'barcelona'
barcelona_weekdays['price_period'] = 'weekday'
barcelona_weekends['city'] = 'barcelona'
barcelona_weekends['price_period'] = 'weekend'

berlin_weekdays['city'] = 'berlin'
berlin_weekdays['price_period'] = 'weekday'
berlin_weekends['city'] = 'berlin'
berlin_weekends['price_period'] = 'weekend'

budapest_weekdays['city'] = 'budapest'
budapest_weekdays['price_period'] = 'weekday'
budapest_weekends['city'] = 'budapest'
budapest_weekends['price_period'] = 'weekend'

lisbon_weekdays['city'] = 'lisbon'
lisbon_weekdays['price_period'] = 'weekday'
lisbon_weekends['city'] = 'lisbon'
lisbon_weekends['price_period'] = 'weekend'

london_weekdays['city'] = 'london'
london_weekdays['price_period'] = 'weekday'
london_weekends['city'] = 'london'
london_weekends['price_period'] = 'weekend'

paris_weekdays['city'] = 'paris'
paris_weekdays['price_period'] = 'weekday'
paris_weekends['city'] = 'paris'
paris_weekends['price_period'] = 'weekend'

rome_weekdays['city'] = 'rome'
rome_weekdays['price_period'] = 'weekday'
rome_weekends['city'] = 'rome'
rome_weekends['price_period'] = 'weekend'

vienna_weekdays['city'] = 'vienna'
vienna_weekdays['price_period'] = 'weekday'
vienna_weekends['city'] = 'vienna'
vienna_weekends['price_period'] = 'weekend'

In [9]:
amsterdam_weekdays.head()

,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,price_period
0,194.033698,Private room,False,True,2.0,False,1,0,10.0,93.0,...,5.022964,2.539380,78.690379,4.166708,98.253896,6.846473,4.90569,52.41772,amsterdam,weekday
1,344.245776,Private room,False,True,4.0,False,0,0,8.0,85.0,...,0.488389,0.239404,631.176378,33.421209,837.280757,58.342928,4.90005,52.37432,amsterdam,weekday
2,264.101422,Private room,False,True,2.0,False,0,1,9.0,87.0,...,5.748312,3.651621,75.275877,3.985908,95.386955,6.646700,4.97512,52.36103,amsterdam,weekday
3,433.529398,Private room,False,True,4.0,False,0,1,9.0,90.0,...,0.384862,0.439876,493.272534,26.119108,875.033098,60.973565,4.89417,52.37663,amsterdam,weekday
4,485.552926,Private room,False,True,2.0,True,0,0,10.0,98.0,...,0.544738,0.318693,552.830324,29.272733,815.305740,56.811677,4.90051,52.37508,amsterdam,weekday

In [12]:
#merge
df = pd.concat([
    amsterdam_weekdays, amsterdam_weekends,
    athens_weekdays, athens_weekends,
    barcelona_weekdays, barcelona_weekends,
    berlin_weekdays, berlin_weekends,
    budapest_weekdays, budapest_weekends,
    lisbon_weekdays, lisbon_weekends,
    london_weekdays, london_weekends,
    paris_weekdays, paris_weekends,
    rome_weekdays, rome_weekends,
    vienna_weekdays, vienna_weekends
], ignore_index=True)

df.shape

(51707, 21)

### Columns an data types

In [13]:
df.dtypes

realSum                       float64
room_type                      object
room_shared                      bool
room_private                     bool
person_capacity               float64
host_is_superhost                bool
multi                           int64
biz                             int64
cleanliness_rating            float64
guest_satisfaction_overall    float64
bedrooms                        int64
dist                          float64
metro_dist                    float64
attr_index                    float64
attr_index_norm               float64
rest_index                    float64
rest_index_norm               float64
lng                           float64
lat                           float64
city                           object
price_period                   object
dtype: object

In [14]:
df.describe()

,realSum,person_capacity,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
count,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.00000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000
mean,279.879591,3.161661,0.291353,0.350204,9.390624,92.628232,1.15876,3.191285,0.681540,294.204105,13.423792,626.856696,22.786177,7.426068,45.671128
std,327.948386,1.298545,0.454390,0.477038,0.954868,8.945531,0.62741,2.393803,0.858023,224.754123,9.807985,497.920226,17.804096,9.799725,5.249263
min,34.779339,2.000000,0.000000,0.000000,2.000000,20.000000,0.00000,0.015045,0.002301,15.152201,0.926301,19.576924,0.592757,-9.226340,37.953000
25%,148.752174,2.000000,0.000000,0.000000,9.000000,90.000000,1.00000,1.453142,0.248480,136.797385,6.380926,250.854114,8.751480,-0.072500,41.399510
50%,211.343089,3.000000,0.000000,0.000000,10.000000,95.000000,1.00000,2.613538,0.413269,234.331748,11.468305,522.052783,17.542238,4.873000,47.506690
75%,319.694287,4.000000,1.000000,1.000000,10.000000,99.000000,1.00000,4.263077,0.737840,385.756381,17.415082,832.628988,32.964603,13.518825,51.471885
max,18545.450285,6.000000,1.000000,1.000000,10.000000,100.000000,10.00000,25.284557,14.273577,4513.563486,100.000000,6696.156772,100.000000,23.786020,52.641410

### Data cleaning

In [18]:
#missing value
df.isnull().any()

realSum                       False
room_type                     False
room_shared                   False
room_private                  False
person_capacity               False
host_is_superhost             False
multi                         False
biz                           False
cleanliness_rating            False
guest_satisfaction_overall    False
bedrooms                      False
dist                          False
metro_dist                    False
attr_index                    False
attr_index_norm               False
rest_index                    False
rest_index_norm               False
lng                           False
lat                           False
city                          False
price_period                  False
dtype: bool

In [20]:
# remove duplicate
print("Duplicates:", df.duplicated().sum())
df = df.drop_duplicates()
print("Shape:", df.shape)

Duplicates: 0
Shape: (51707, 21)

In [26]:
# bedrooms should be whole number
df['bedrooms'] = df['bedrooms'].astype(int) 
df['city'] = df['city'].astype('category')
df['room_type'] = df['room_type'].astype('category')
df['price_period'] = df['price_period'].astype('category')

df.dtypes

realSum                        float64
room_type                     category
room_shared                       bool
room_private                      bool
person_capacity                float64
host_is_superhost                 bool
multi                            int64
biz                              int64
cleanliness_rating             float64
guest_satisfaction_overall     float64
bedrooms                         int64
dist                           float64
metro_dist                     float64
attr_index                     float64
attr_index_norm                float64
rest_index                     float64
rest_index_norm                float64
lng                            float64
lat                            float64
city                          category
price_period                  category
dtype: object

In [27]:
df['realSum'].describe()

count    51707.000000
mean       279.879591
std        327.948386
min         34.779339
25%        148.752174
50%        211.343089
75%        319.694287
max      18545.450285
Name: realSum, dtype: float64

In [28]:
# max is way higher than the 75th percentile, 
# price column has some expensive listings that might distort the charts and the model later
# use the IQR rule to cut them off.
Q1 = df['realSum'].quantile(0.25)
Q3 = df['realSum'].quantile(0.75)
IQR = Q3 - Q1
upper_limit = Q3 + 1.5 * IQR
print("Upper limit:", upper_limit)

before = len(df)
df = df[df['realSum'] <= upper_limit]
after = len(df)
print(f"Removed {before - after} outlier rows")
print("New shape:", df.shape)

Upper limit: 576.1074557199221
Removed 3662 outlier rows
New shape: (48045, 21)

In [30]:
# save
df.to_csv('../airbnb/data/clean_data/airbnb_cleaned.csv', index=False)
print("Saved:", df.shape)

Saved: (48045, 21)